// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['transformation']['Ref']['Cancel']();
}

export function Confirm() {
  return window['go']['transformation']['Ref']['Confirm']();
}

export function IsActive() {
  return window['go']['transformation']['Ref']['IsActive']();
}

export function OnStartup(arg1) {
  return window['go']['transformation']['Ref']['OnStartup'](arg1);
}

export function RefashionArmor(arg1, arg2) {
  return window['go']['transformation']['Ref']['RefashionArmor'](arg1, arg2);
}

export function RefashionWeapon(arg1, arg2) {
  return window['go']['transformation']['Ref']['RefashionWeapon'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['transformation']['Ref']['SetContext'](arg1);
}
