// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Cancel():Promise<void>;

export function Confirm():Promise<void>;

export function IsActive():Promise<boolean>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RefashionArmor(arg1:number,arg2:Array<number>):Promise<void>;

export function RefashionWeapon(arg1:number,arg2:Array<number>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
