// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCoverImage(arg1, arg2) {
  return window['go']['main']['App']['AddCoverImage'](arg1, arg2);
}

export function AddLog(arg1) {
  return window['go']['main']['App']['AddLog'](arg1);
}

export function AddModPreview(arg1, arg2) {
  return window['go']['main']['App']['AddModPreview'](arg1, arg2);
}

export function AddSubModPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSubModPreview'](arg1, arg2, arg3);
}

export function BatchGenerateModCards(arg1) {
  return window['go']['main']['App']['BatchGenerateModCards'](arg1);
}

export function CheckAllModConflicts() {
  return window['go']['main']['App']['CheckAllModConflicts']();
}

export function CheckModConflicts(arg1) {
  return window['go']['main']['App']['CheckModConflicts'](arg1);
}

export function CheckModEngine() {
  return window['go']['main']['App']['CheckModEngine']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DetectGameRoot() {
  return window['go']['main']['App']['DetectGameRoot']();
}

export function DisableHdrSubMod(arg1, arg2) {
  return window['go']['main']['App']['DisableHdrSubMod'](arg1, arg2);
}

export function DisableHdrSubModAndRefresh(arg1, arg2) {
  return window['go']['main']['App']['DisableHdrSubModAndRefresh'](arg1, arg2);
}

export function DisableMod(arg1) {
  return window['go']['main']['App']['DisableMod'](arg1);
}

export function DisableModAndRefresh(arg1) {
  return window['go']['main']['App']['DisableModAndRefresh'](arg1);
}

export function EnableHdrSubMod(arg1, arg2) {
  return window['go']['main']['App']['EnableHdrSubMod'](arg1, arg2);
}

export function EnableHdrSubModAndRefresh(arg1, arg2) {
  return window['go']['main']['App']['EnableHdrSubModAndRefresh'](arg1, arg2);
}

export function EnableMod(arg1) {
  return window['go']['main']['App']['EnableMod'](arg1);
}

export function EnableModAndRefresh(arg1) {
  return window['go']['main']['App']['EnableModAndRefresh'](arg1);
}

export function GenerateSubModModJson(arg1) {
  return window['go']['main']['App']['GenerateSubModModJson'](arg1);
}

export function GetAbout() {
  return window['go']['main']['App']['GetAbout']();
}

export function GetArmorParts() {
  return window['go']['main']['App']['GetArmorParts']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEnginePath() {
  return window['go']['main']['App']['GetEnginePath']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetModConfig(arg1) {
  return window['go']['main']['App']['GetModConfig'](arg1);
}

export function GetModPreviews(arg1) {
  return window['go']['main']['App']['GetModPreviews'](arg1);
}

export function GetMods() {
  return window['go']['main']['App']['GetMods']();
}

export function GetSubModPreviews(arg1, arg2) {
  return window['go']['main']['App']['GetSubModPreviews'](arg1, arg2);
}

export function GetWeaponParts() {
  return window['go']['main']['App']['GetWeaponParts']();
}

export function ImportMod(arg1) {
  return window['go']['main']['App']['ImportMod'](arg1);
}

export function InstallHdrMod(arg1) {
  return window['go']['main']['App']['InstallHdrMod'](arg1);
}

export function InstallMod(arg1, arg2) {
  return window['go']['main']['App']['InstallMod'](arg1, arg2);
}

export function InstallModEngine() {
  return window['go']['main']['App']['InstallModEngine']();
}

export function IsGameRunning() {
  return window['go']['main']['App']['IsGameRunning']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function ListFolderImages(arg1) {
  return window['go']['main']['App']['ListFolderImages'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function ReadModConfig(arg1) {
  return window['go']['main']['App']['ReadModConfig'](arg1);
}

export function RefreshGameMods() {
  return window['go']['main']['App']['RefreshGameMods']();
}

export function RefreshModPreviews(arg1) {
  return window['go']['main']['App']['RefreshModPreviews'](arg1);
}

export function RemoveModPreview(arg1, arg2) {
  return window['go']['main']['App']['RemoveModPreview'](arg1, arg2);
}

export function RemoveModRecord(arg1) {
  return window['go']['main']['App']['RemoveModRecord'](arg1);
}

export function RemoveSubModPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveSubModPreview'](arg1, arg2, arg3);
}

export function ScanMods() {
  return window['go']['main']['App']['ScanMods']();
}

export function SearchNioh2Root() {
  return window['go']['main']['App']['SearchNioh2Root']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SetGameRoot(arg1) {
  return window['go']['main']['App']['SetGameRoot'](arg1);
}

export function SetModCategory(arg1, arg2) {
  return window['go']['main']['App']['SetModCategory'](arg1, arg2);
}

export function SetModCover(arg1, arg2) {
  return window['go']['main']['App']['SetModCover'](arg1, arg2);
}

export function SetModNickname(arg1, arg2) {
  return window['go']['main']['App']['SetModNickname'](arg1, arg2);
}

export function SetModParts(arg1, arg2) {
  return window['go']['main']['App']['SetModParts'](arg1, arg2);
}

export function SetModsRepo(arg1) {
  return window['go']['main']['App']['SetModsRepo'](arg1);
}

export function SetSubModCover(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSubModCover'](arg1, arg2, arg3);
}

export function SetSubModParts(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSubModParts'](arg1, arg2, arg3);
}

export function SetUpdateUrl(arg1) {
  return window['go']['main']['App']['SetUpdateUrl'](arg1);
}

export function StopGame() {
  return window['go']['main']['App']['StopGame']();
}

export function UninstallMod(arg1) {
  return window['go']['main']['App']['UninstallMod'](arg1);
}

export function WriteModCard(arg1, arg2) {
  return window['go']['main']['App']['WriteModCard'](arg1, arg2);
}
