// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {armordata} from '../models';

export function AddCoverImage(arg1:string,arg2:string):Promise<string>;

export function AddLog(arg1:string):Promise<Array<config.LogEntry>>;

export function AddModPreview(arg1:string,arg2:string):Promise<string>;

export function AddSubModPreview(arg1:string,arg2:string,arg3:string):Promise<string>;

export function BatchGenerateModCards(arg1:string):Promise<main.BatchGenerateResult>;

export function CheckAllModConflicts():Promise<Array<main.ModConflictInfo>>;

export function CheckModConflicts(arg1:string):Promise<Array<main.ModConflict>>;

export function CheckModEngine():Promise<main.EngineStatus>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ClearLogs():Promise<void>;

export function DetectGameRoot():Promise<string>;

export function DisableHdrSubMod(arg1:string,arg2:string):Promise<void>;

export function DisableHdrSubModAndRefresh(arg1:string,arg2:string):Promise<void>;

export function DisableMod(arg1:string):Promise<void>;

export function DisableModAndRefresh(arg1:string):Promise<void>;

export function EnableHdrSubMod(arg1:string,arg2:string):Promise<void>;

export function EnableHdrSubModAndRefresh(arg1:string,arg2:string):Promise<void>;

export function EnableMod(arg1:string):Promise<void>;

export function EnableModAndRefresh(arg1:string):Promise<void>;

export function GenerateSubModModJson(arg1:string):Promise<void>;

export function GetAbout():Promise<Array<main.AboutInfo>>;

export function GetArmorParts():Promise<Array<armordata.Slot>>;

export function GetConfig():Promise<config.App>;

export function GetEnginePath():Promise<string>;

export function GetLogs():Promise<Array<config.LogEntry>>;

export function GetModConfig(arg1:string):Promise<main.ImportResult>;

export function GetModPreviews(arg1:string):Promise<Array<string>>;

export function GetMods():Promise<Array<config.ModInfo>>;

export function GetSubModPreviews(arg1:string,arg2:string):Promise<Array<string>>;

export function GetWeaponParts():Promise<Array<armordata.Part>>;

export function ImportMod(arg1:string):Promise<main.ImportResult>;

export function InstallHdrMod(arg1:string):Promise<main.ImportResult>;

export function InstallMod(arg1:string,arg2:Record<string, Array<string>>):Promise<void>;

export function InstallModEngine():Promise<void>;

export function LaunchGame():Promise<void>;

export function ListFolderImages(arg1:string):Promise<Array<string>>;

export function OpenDirectory(arg1:string):Promise<void>;

export function ReadModConfig(arg1:string):Promise<main.ImportResult>;

export function RefreshGameMods():Promise<boolean>;

export function RefreshModPreviews(arg1:string):Promise<Array<string>>;

export function RemoveModPreview(arg1:string,arg2:string):Promise<void>;

export function RemoveModRecord(arg1:string):Promise<void>;

export function RemoveSubModPreview(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanMods():Promise<Array<config.ModInfo>>;

export function SearchNioh2Root():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SetGameRoot(arg1:string):Promise<void>;

export function SetModCategory(arg1:string,arg2:string):Promise<void>;

export function SetModCover(arg1:string,arg2:string):Promise<string>;

export function SetModNickname(arg1:string,arg2:string):Promise<void>;

export function SetModParts(arg1:string,arg2:Record<string, Array<string>>):Promise<void>;

export function SetModsRepo(arg1:string):Promise<void>;

export function SetSubModCover(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSubModParts(arg1:string,arg2:string,arg3:Record<string, Array<string>>):Promise<void>;

export function SetUpdateUrl(arg1:string):Promise<void>;

export function UninstallMod(arg1:string):Promise<void>;

export function WriteModCard(arg1:string,arg2:main.ModCard):Promise<main.ImportResult>;
